# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f3fbf198a02fe3387f735e42d82aac7bee8bacc924ecd42f493786c6ce500163893fbd97200e40b530e9b4954af19a96b08bbb73324038662fc3efd4dd1df6a

test:
  secret_key_base: 6f0420d732281eafb90aff7a05b29b7cab10d620b6a88a82caafdff184b719add69c5be54f288e2a1e71b7064079c27170a7dd981e8dc5958503fc1a56fd9364

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
